### ISSUE TITLE
Why laser_scan and Odometry is not synchronous?

### ISSUE THREAD

**Issue by flybirdtian** [rakeshshrestha31/ground_truth_layer#2]
@rakeshshrestha31  I see that you have already used TimeSynchronizer to sync the laser_scan and Odometry, why the robot pose is still not synchronous with laser_scan, since both of them are ground truth?

**Comment by rakeshshrestha31** [comment]
A bit overdue, but the custom stage interface used in [stage_frontier_datagen](https://github.com/rakeshshrestha31/stage_frontier_datagen) along with commit https://github.com/rakeshshrestha31/Stage/commit/14dd84358c8cebc65ce943e73041f8025928e614 solves this problem.
